import turtle
from math import sqrt
delka = 100
odvesna = sqrt(delka ** 2 + delka ** 2)
ws = turtle.Screen()
julie = turtle.Turtle()
julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(135)
julie.forward(odvesna)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna)
julie.right(135)
julie.forward(delka)

julie.penup()
julie.right(180)
julie.forward(3*delka)

julie.pendown()
julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(135)
julie.forward(odvesna)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna)
julie.right(135)
julie.forward(delka)

julie.penup()
julie.right(180)
julie.forward(3*delka)
julie.pendown()

julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(90)
julie.forward(delka)
julie.left(135)
julie.forward(odvesna)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna/2)
julie.left(90)
julie.forward(odvesna)
julie.right(135)
julie.forward(delka)

ws.exitonclick()